// angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"]
})
export class AppComponent {
    isPopupVisible: boolean;

    constructor() {
        this.isPopupVisible = true;
    }

    togglePopup(): void {
        this.isPopupVisible = !this.isPopupVisible;
    }
}

<dx-button text="Open popup" (onClick)="togglePopup()"></dx-button>
<dx-popup
    [(visible)]="isPopupVisible"
    [closeOnOutsideClick]="true"
    [showTitle]="true"
    title="Information"
    [height]="500"
    [width]="500"
    [dragEnabled]="true"
>
    <div *dxTemplate="let data of 'content'">
        <dx-scroll-view width="100%" height="100%">
            <img src="assets/images/dx-logo.png" alt="logo">
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Penatibus et magnis dis parturient. Eget dolor morbi non arcu risus. Tristique magna sit amet purus gravida quis blandit.
                Auctor urna nunc id cursus metus aliquam eleifend mi in. Tellus orci ac auctor augue mauris augue neque gravida. Nullam vehicula ipsum a arcu.
                Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Cursus in hac habitasse platea dictumst. Egestas dui id ornare arcu.
                Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim.
            </p>
            <p>
                Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Neque volutpat ac tincidunt vitae semper quis lectus.
                Sed sed risus pretium quam vulputate dignissim suspendisse in. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar.
                Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Amet cursus sit amet dictum sit amet justo donec enim.
                Vestibulum rhoncus est pellentesque elit ullamcorper. Id aliquet risus feugiat in ante metus dictum at.
            </p>
        </dx-scroll-view>
    </div>
</dx-popup>

// react/src/App.js
import React, { useState } from "react";
import logo from "./assets/images/dx-logo.png";

import "devextreme/dist/css/dx.common.css";
import "devextreme/dist/css/dx.light.css";

import { Popup, Button, ScrollView } from "devextreme-react";

const App = () => {
    const [isPopupVisible, setPopupVisivility] = useState(true);

    const togglePopup = () => {
        setPopupVisivility(!isPopupVisible);
    };

    return (
        <>
            <Button text="Open popup" onClick={togglePopup} />
            <Popup
                visible={isPopupVisible}
                closeOnOutsideClick={true}
                onHiding={togglePopup}
                showTitle={true}
                title="Information"
                width={500}
                height={500}
                dragEnabled={true}>
                <ScrollView height="100%" width="100%">
                    <img src={logo} alt="logo" />
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua. Penatibus et magnis dis parturient. Eget
                        dolor morbi non arcu risus. Tristique magna sit amet
                        purus gravida quis blandit. Auctor urna nunc id cursus
                        metus aliquam eleifend mi in. Tellus orci ac auctor
                        augue mauris augue neque gravida. Nullam vehicula ipsum
                        a arcu. Nullam ac tortor vitae purus faucibus ornare
                        suspendisse sed nisi. Cursus in hac habitasse platea
                        dictumst. Egestas dui id ornare arcu. Dictumst
                        vestibulum rhoncus est pellentesque elit ullamcorper
                        dignissim.
                    </p>
                    <p>
                        Mauris rhoncus aenean vel elit scelerisque mauris
                        pellentesque pulvinar. Neque volutpat ac tincidunt vitae
                        semper quis lectus. Sed sed risus pretium quam vulputate
                        dignissim suspendisse in. Urna nec tincidunt praesent
                        semper feugiat nibh sed pulvinar. Ultricies lacus sed
                        turpis tincidunt id aliquet risus feugiat. Amet cursus
                        sit amet dictum sit amet justo donec enim. Vestibulum
                        rhoncus est pellentesque elit ullamcorper. Id aliquet
                        risus feugiat in ante metus dictum at.
                    </p>
                </ScrollView>
            </Popup>
        </>
    );
};
export default App;
